
CREATE TABLE `dragoLog` (
  `datetime` datetime NOT NULL,
  `RPL` smallint(6) NOT NULL,
  `rpc4` int(11) DEFAULT NULL,
  `rpc5` int(11) DEFAULT NULL,
  `rpc6` int(11) DEFAULT NULL,
  `rpc7` int(11) DEFAULT NULL,
  `rpc8` int(11) DEFAULT NULL,
  `rpc9` int(11) DEFAULT NULL,
  `rpc11` int(11) DEFAULT NULL,
  `rpc12` int(11) DEFAULT NULL,
  `rpc13` int(11) DEFAULT NULL,
  `rpc14` int(11) DEFAULT NULL,
  `rpc15` int(11) DEFAULT 0,
  `rpc16` int(11) DEFAULT 0,
  `rpc17` int(11) DEFAULT 0,
  `rpc18` int(11) DEFAULT 0,
  `mitmUnknown` int(11) DEFAULT NULL,
  `mitmNoGame` int(11) DEFAULT NULL,
  `mitmLogginIn` int(11) DEFAULT NULL,
  `mitmTokenRej` int(11) DEFAULT NULL,
  `mitmNotLogged` int(11) DEFAULT NULL,
  `mitmLoginErr` int(11) DEFAULT NULL,
  `noGMO` int(11) DEFAULT NULL,
  `proxyBan` int(11) DEFAULT NULL,
  `wsError` int(11) DEFAULT NULL,
  `wsClose` int(11) DEFAULT NULL,
  `wsMitmRecon` int(11) DEFAULT NULL,
  `gmoPoke` int(11) DEFAULT NULL,
  `gmo0` int(11) DEFAULT NULL,
  `gmo1` int(11) DEFAULT NULL,
  `gmo2` int(11) DEFAULT NULL,
  `gmo3` int(11) DEFAULT NULL,
  `gmo4` int(11) DEFAULT NULL,
  `gmo5` int(11) DEFAULT NULL,
  `gmo6` int(11) DEFAULT NULL,
  `gmo7` int(11) DEFAULT NULL,
  `gmo8` int(11) DEFAULT NULL,
  `authReq` int(11) DEFAULT NULL,
  `authed` int(11) DEFAULT NULL,
  `login` int(11) DEFAULT NULL,
  `swWarnSusp` int(11) DEFAULT NULL,
  `swBanned` int(11) DEFAULT NULL,
  `swDisabled` int(11) DEFAULT NULL,
  `swDayLimit` int(11) DEFAULT NULL,
  `swRange` int(11) DEFAULT NULL,
  `swTime` int(11) DEFAULT NULL,
  `backoff` int(11) DEFAULT NULL,
  `released24h` int(11) DEFAULT 0,
  `released7d` int(11) DEFAULT 0,
  `workers` int(11) DEFAULT NULL,
  `locations` int(11) DEFAULT NULL,
  `totalProtoTime` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`datetime`,`RPL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `dragoLog_fort` (
  `datetime` datetime NOT NULL,
  `RPL` smallint(6) NOT NULL,
  `rpc4` int(11) DEFAULT NULL,
  `rpc5` int(11) DEFAULT NULL,
  `rpc6` int(11) DEFAULT NULL,
  `rpc7` int(11) DEFAULT NULL,
  `rpc8` int(11) DEFAULT NULL,
  `rpc9` int(11) DEFAULT NULL,
  `rpc11` int(11) DEFAULT NULL,
  `rpc12` int(11) DEFAULT NULL,
  `rpc13` int(11) DEFAULT NULL,
  `rpc14` int(11) DEFAULT NULL,
  `rpc15` int(11) DEFAULT 0,
  `rpc16` int(11) DEFAULT 0,
  `rpc17` int(11) DEFAULT 0,
  `rpc18` int(11) DEFAULT 0,
  `noGMO` int(11) DEFAULT NULL,
  `gmoPoke` int(11) DEFAULT NULL,
  `gmo0` int(11) DEFAULT NULL,
  `gmo1` int(11) DEFAULT NULL,
  `gmo2` int(11) DEFAULT NULL,
  `gmo3` int(11) DEFAULT NULL,
  `gmo4` int(11) DEFAULT NULL,
  `gmo5` int(11) DEFAULT NULL,
  `gmo6` int(11) DEFAULT NULL,
  `gmo7` int(11) DEFAULT NULL,
  `gmo8` int(11) DEFAULT NULL,
  `swWarnSusp` int(11) DEFAULT NULL,
  `swBanned` int(11) DEFAULT NULL,
  `swDisabled` int(11) DEFAULT NULL,
  `swDayLimit` int(11) DEFAULT NULL,
  `swRange` int(11) DEFAULT NULL,
  `swTime` int(11) DEFAULT NULL,
  `backoff` int(11) DEFAULT NULL,
  PRIMARY KEY (`datetime`,`RPL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stats_worker_fort` (
  `datetime` datetime NOT NULL,
  `rpl` smallint(6) NOT NULL,
  `worker` varchar(255) NOT NULL,
  `fetchRaid` int(11) DEFAULT NULL,
  `modeLocations` int(11) DEFAULT NULL,
  `gotGMO` int(11) DEFAULT NULL,
  `fortLookup` int(11) DEFAULT NULL,
  `totalProtoTimeFort` int(11) DEFAULT 0,
  `totalProtoTimeRaid` int(11) DEFAULT 0,
  PRIMARY KEY (`datetime`,`rpl`,`worker`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stats_prioraid` (
  `datetime` datetime NOT NULL,
  `rpl` smallint(6) NOT NULL,
  `scanCount` int(11) DEFAULT 0,
  `scanMin` int(11) DEFAULT 0,
  `scanMax` int(11) DEFAULT 0,
  `scanAvg` int(11) DEFAULT 0,
  `raidMin` int(11) DEFAULT 0,
  `raidMax` int(11) DEFAULT 0,
  `raidAvg` int(11) DEFAULT 0,
  `raidActiveMin` int(11) DEFAULT 0,
  `raidActiveMax` int(11) DEFAULT 0,
  `raidActiveAvg` int(11) DEFAULT 0,
  `raidQueueMin` int(11) DEFAULT 0,
  `raidQueueMax` int(11) DEFAULT 0,
  `raidQueueAvg` int(11) DEFAULT 0,
  `Qcount` int(11) DEFAULT 0,
  PRIMARY KEY (`datetime`,`rpl`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE  `stats_worker`
  ADD COLUMN `mode` varchar(255) NOT NULL AFTER `controller_worker`,
  ADD COLUMN `distance` float DEFAULT 0,
  ADD COLUMN `retries` int DEFAULT 0,
  ADD COLUMN `timeElapsed` float DEFAULT 0,
  ADD COLUMN `locationDelay` float DEFAULT 0,
  ADD COLUMN `gmos` int DEFAULT 0,
  ADD COLUMN `gmoInitialSuccess` int DEFAULT 0,
  ADD COLUMN `gmo0fail` int DEFAULT 0,
  ADD COLUMN `gmo1fail` int DEFAULT 0,
  ADD COLUMN `gmo2fail` int DEFAULT 0,
  ADD COLUMN `gmo3fail` int DEFAULT 0,
  ADD COLUMN `gmo4fail` int DEFAULT 0,
  ADD COLUMN `gmo5fail` int DEFAULT 0,
  ADD COLUMN `gmo6fail` int DEFAULT 0,
  ADD COLUMN `gmo7fail` int DEFAULT 0,
  ADD COLUMN `gmo8fail` int DEFAULT 0,
  ADD COLUMN `gmoNoCell` int DEFAULT 0,
  ADD COLUMN `gmoGivingUp` int DEFAULT 0,
  ADD COLUMN `gmoDelay` float DEFAULT 0;

CREATE TABLE `stats_account` (
  `datetime` datetime NOT NULL,
  `account` varchar(255) NOT NULL,
  `worker` varchar(255) NOT NULL,
  `DISK_ENCOUNTER` int(11) DEFAULT NULL,
  `GET_HOLOHOLO_INVENTORY` int(11) DEFAULT NULL,
  `GET_PLAYER` int(11) DEFAULT NULL,
  `GET_MAP_OBJECTS` int(11) DEFAULT NULL,
  `ENCOUNTER` int(11) DEFAULT NULL,
  `FORT_DETAILS` int(11) DEFAULT NULL,
  `GYM_GET_INFO` int(11) DEFAULT NULL,
  `RECYCLE_INVENTORY_ITEM` int(11) DEFAULT NULL,
  `REMOVE_QUEST` int(11) DEFAULT NULL,
  `FORT_SEARCH` int(11) DEFAULT NULL,
  `GET_RAID_LOBBY_COUNTER` int(11) DEFAULT NULL,
  `duration` int(11) DEFAULT 0,
  PRIMARY KEY (`datetime`,`account`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- update db version
UPDATE version set version = 6 where version.key = 'blissey';
