CREATE TABLE IF NOT EXISTS `stats_invasion` (
  `datetime` datetime NOT NULL,
  `rpl` smallint(6) NOT NULL,
  `workers` int default NULL,
  `avgTime` int default NULL,
  `detect` int(11) DEFAULT NULL,
  `failed` int default NULL,
  `done` int(11) DEFAULT NULL,
  `expired` int(11) DEFAULT NULL,
  `qmin` int(11) DEFAULT NULL,
  `qmax` int(11) DEFAULT NULL,
  `qavg` int(11) DEFAULT NULL,
  `grLine` int(11) DEFAULT NULL,
  `leLine` int(11) DEFAULT NULL,
  `giConf` int(11) DEFAULT NULL,
  `giLine` int(11) DEFAULT NULL,
  `gmin` decimal(5,2),
  `gmax` decimal(5,2),
  `gavg` decimal(5,2),
  `lmin` decimal(5,2),
  `lmax` decimal(5,2),
  `lavg` decimal(5,2),
  PRIMARY KEY (`datetime`,`rpl`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `dragoLog_invasion` (
  `datetime` datetime NOT NULL,
  `RPL` smallint(6) NOT NULL,
  `rpc4` int(11) DEFAULT NULL,
  `rpc5` int(11) DEFAULT NULL,
  `rpc6` int(11) DEFAULT NULL,
  `rpc7` int(11) DEFAULT NULL,
  `rpc8` int(11) DEFAULT NULL,
  `rpc9` int(11) DEFAULT NULL,
  `rpc11` int(11) DEFAULT NULL,
  `rpc12` int(11) DEFAULT NULL,
  `rpc13` int(11) DEFAULT NULL,
  `rpc14` int(11) DEFAULT NULL,
  `rpc15` int(11) default NULL,
  `rpc16` int(11) default NULL,
  `rpc17` int(11) default NULL,
  `rpc18` int(11) default NULL,
  `noGMO` int(11) DEFAULT NULL,
  `gmoPoke` int(11) DEFAULT NULL,
  `gmo0` int(11) DEFAULT NULL,
  `gmo1` int(11) DEFAULT NULL,
  `gmo2` int(11) DEFAULT NULL,
  `gmo3` int(11) DEFAULT NULL,
  `gmo4` int(11) DEFAULT NULL,
  `gmo5` int(11) DEFAULT NULL,
  `gmo6` int(11) DEFAULT NULL,
  `gmo7` int(11) DEFAULT NULL,
  `gmo8` int(11) DEFAULT NULL,
  `swWarnSusp` int(11) DEFAULT NULL,
  `swBanned` int(11) DEFAULT NULL,
  `swDisabled` int(11) DEFAULT NULL,
  `swDayLimit` int(11) DEFAULT NULL,
  `swRange` int(11) DEFAULT NULL,
  `swTime` int(11) DEFAULT NULL,
  `backoff` int(11) DEFAULT NULL,
  PRIMARY KEY (`datetime`,`RPL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- update db version
UPDATE version set version = 9 where version.key = 'blissey';
