{
 "title": "06. Account stats",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "5m,15m,1h,1d,7d" },
   {
    "name": "mode",
    "query": "select mode from stats_accounts group by mode"
   }
  ]
 },
 "panels": [
  { "title": "All modes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Account rotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "backend",
     "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\nsum(case when json_extract(counts, '$.METHOD_ENCOUNTER') is not NULL or json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then 1 end) as 'normal disabled',\r\nsum(case when json_extract(counts, '$.METHOD_ENCOUNTER') is NULL and json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is NULL then 1 end) as 'instant rotation',\r\navg(case when json_extract(counts, '$.METHOD_ENCOUNTER') is not NULL or json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then duration_ms/3600000 end) as 'Average duration'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Instant rotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "backend",
     "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\nsum(case when json_extract(counts, '$.METHOD_ENCOUNTER') is not NULL or json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then 1 end) as 'normal disabled',\r\nsum(case when json_extract(counts, '$.METHOD_ENCOUNTER') is NULL and json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is NULL then 1 end) as 'instant rotation',\r\navg(case when json_extract(counts, '$.METHOD_ENCOUNTER') is not NULL or json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then duration_ms/3600000 end) as 'Average duration'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Rotation reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "backend",
     "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\ncase when reason_for_session_end like 'ErrGo failed to detect lineup for invasion%' then 'ErrGo failed to detect lineup for invasion' else reason_for_session_end end as 'reason_end',\r\ncount(reason_for_session_end) as '.'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end)\r\nGROUP BY 1,reason_end\r\nORDER BY 1"
    }
   ]
  },
  { "title": "Area mode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Account rotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "backend",
     "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\nsum(case when json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then 1 end) as 'normal disabled',\r\nsum(case when json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is NULL then 1 end) as 'instant rotation',\r\navg(case when json_extract(counts, '$.METHOD_ENCOUNTER') is not NULL then json_extract(counts, '$.METHOD_ENCOUNTER') end) as 'Average encounters',\r\navg(case when json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') end) as 'Average gmo',\r\navg(case when json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then duration_ms/3600000 end) as 'Average duration'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end) and\r\nmode in ('PokemonMode','QuestMode')\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Instant rotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Average GetMapObjects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Average Encounter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Average duration (hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Rotation reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "dataset": "backend",
     "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\nreason_for_session_end,\r\ncount(reason_for_session_end) as '.'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end) and\r\nmode='PokemonMode'\r\nGROUP BY 1,reason_for_session_end\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Invasion mode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Account rotations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "dataset": "backend",
       "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\nsum(case when json_extract(counts, '$.METHOD_INVASION_OPEN_COMBAT_SESSION') is not NULL then 1 end) as 'normal disabled',\r\nsum(case when json_extract(counts, '$.METHOD_INVASION_OPEN_COMBAT_SESSION') is NULL then 1 end) as 'instant rotation',\r\navg(case when json_extract(counts, '$.METHOD_INVASION_OPEN_COMBAT_SESSION') is not NULL then json_extract(counts, '$.METHOD_INVASION_OPEN_COMBAT_SESSION') end) as 'Average open combat',\r\navg(case when json_extract(counts, '$.METHOD_INVASION_OPEN_COMBAT_SESSION') is not NULL then duration_ms/3600000 end) as 'Average duration'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end) and\r\nmode='InvasionMode'\r\nGROUP BY 1\r\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Instant rotations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      { "panelId": 21 }
     ]
    },
    {
     "title": "Average METHOD_INVASION_OPEN_COMBAT_SESSION",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      { "panelId": 21 }
     ]
    },
    {
     "title": "Rotation reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "dataset": "backend",
       "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\ncase when reason_for_session_end like 'ErrGo failed to detect lineup for invasion%' then 'ErrGo failed to detect lineup for invasion' else reason_for_session_end end as 'reason_end',\r\ncount(reason_for_session_end) as '.'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end) and\r\nmode='InvasionMode'\r\nGROUP BY 1,reason_end\r\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Average duration (hours)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      { "panelId": 21 }
     ]
    }
   ]
  },
  {
   "title": "Fort mode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Account rotations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "dataset": "backend",
       "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\nsum(case when json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then 1 end) as 'normal disabled',\r\nsum(case when json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is NULL then 1 end) as 'instant rotation',\r\navg(case when json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') end) as 'Average gmo',\r\navg(case when json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL then duration_ms/3600000 end) as 'Average duration'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end) and\r\nmode='FortMode'\r\nGROUP BY 1\r\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Instant rotations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      { "panelId": 27 }
     ]
    },
    {
     "title": "Average GMO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      { "panelId": 27 }
     ]
    },
    {
     "title": "Rotation reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "dataset": "backend",
       "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\nreason_for_session_end,\r\ncount(reason_for_session_end) as '.'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end) and\r\nmode='FortMode'\r\nGROUP BY 1,reason_for_session_end\r\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Average duration (hours)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      { "panelId": 27 }
     ]
    }
   ]
  },
  { "title": "distribution (mode var)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Rotation reason",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "backend",
     "rawSql": "select\r\n$__timeGroup(session_end,$interval) as 'time',\r\ncase\r\n  when reason_for_session_end like 'ErrGo failed to detect lineup for invasion%' then 'ErrGo failed to detect lineup for invasion' \r\n  when reason_for_session_end='ErrDisabled' and (json_extract(counts, '$.METHOD_ENCOUNTER') is not NULL or json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is not NULL) then 'ErrDisabled'\r\n  when reason_for_session_end='ErrDisabled' and (json_extract(counts, '$.METHOD_ENCOUNTER') is NULL and json_extract(counts, '$.METHOD_GET_MAP_OBJECTS') is NULL) then 'instantRotation (rpc18?)'\r\n  else reason_for_session_end\r\nend as 'reason_end',\r\ncount(reason_for_session_end) as '.'\r\nfrom stats_accounts\r\nwhere\r\n$__timeFilter(session_end) and mode in ($mode)\r\nGROUP BY reason_end\r\nORDER BY 1"
    }
   ]
  }
 ]
}