{
 "title": "09. Fort mode stats",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RPL",
    "query": "select distinct(RPL) from stats_worker_fort;"
   },
   {
    "name": "drago_worker",
    "query": "select controller_worker from stats_worker where rpl=5 and  datetime>now() - interval 30 day and mode = 'FortMode';"
   }
  ]
 },
 "panels": [
  {
   "title": "Worker stats (from d2 worker stats)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Location handling time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(Datetime,$__interval) AS \"time\",\r\n  count(controller_worker) as 'fort: workers',\r\n  sum(loc_time)/sum(loc_success) AS \"fort: Location handling time\",\r\n  sum(loc_count) AS \"fort: Locations handled\",\r\n  100*sum(loc_success)/sum(loc_count) AS \"fort: Location success rate\",\r\n  sum(gmos) as \"fort: total GMOs\",\r\n  sum(retries) as \"fort: retries\",\r\n  sum(timeElapsed)/sum(loc_count) as \"fort: proto time\",\r\n  sum(locationDelay)/(sum(locationDelay)+sum(timeElapsed)) as \"fort: rate location delay\",\r\n  (0.25*(sum(retries)-sum(gmoNoCell)))/(sum(locationDelay)+sum(timeElapsed)) as \"fort: rate gmo no pokemon delay\",\r\n  (0.5*sum(gmoNoCell))/(sum(locationDelay)+sum(timeElapsed)) as \"fort: rate gmo no cell delay\",\r\n  (sum(timeElapsed)-(0.5*sum(gmoNoCell))-(0.25*(sum(retries)-sum(gmoNoCell))))/(sum(locationDelay)+sum(timeElapsed)) as \"fort: real proto time\",\r\n  sum(gmoGivingUp) as \"fort: GMO giving up\",\r\n  (sum(gmo0fail)-sum(gmo1fail))/sum(gmo0fail) as 'GMO success after retry #1',\r\n  (sum(gmo1fail)-sum(gmo2fail))/sum(gmo0fail) as '#2',\r\n  (sum(gmo2fail)-sum(gmo3fail))/sum(gmo0fail) as '#3',\r\n  (sum(gmo3fail)-sum(gmo4fail))/sum(gmo0fail) as '#4',\r\n  (sum(gmo4fail)-sum(gmo5fail))/sum(gmo0fail) as '#5',\r\n  (sum(gmo5fail)-sum(gmo6fail))/sum(gmo0fail) as '#6',\r\n  (sum(gmo6fail)-sum(gmo7fail))/sum(gmo0fail) as '#7',\r\n  (sum(gmo7fail)-sum(gmo8fail))/sum(gmo0fail) as '#8',\r\n  100*sum(gmoInitialSuccess)/sum(loc_count) as 'fort: gmo initial success rate',\r\n  100*sum(gmoGivingUp)/sum(loc_count) as 'fort: gmo failure rate'\r\nFROM stats_worker\r\nWHERE\r\n  $__timeFilter(Datetime) and\r\n  RPL='$RPL' and\r\n  controller_worker in ($drago_worker)\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Time spend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Location handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Location handling success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "GMO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "GMO repeated attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "GMO totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "GMO giving up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Worker stats (from d2 log processing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "Fort mode location handling time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(Datetime,$__interval) as 'time',\n  sum(modeLocations) as 'fort mode locations handled',\n  sum(fetchRaid) as 'raid locations handled',\n  sum(fortLookup) as 'fort lookups',\n  sum(totalProtoTimeFort)/sum(modeLocations) as 'fort mode location handling time (ms)',\n  sum(totalProtoTimeRaid)/sum(fetchRaid) as 'raid location handling time (ms)'\n\nFROM stats_worker_fort\nWHERE\n  $__timeFilter(datetime) and\n  RPL = '$RPL' AND\n  worker in ($drago_worker) \nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Fort mode locations handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Raid location handling time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Raid locations handed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  { "title": "Area stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Raid scanned within x minutes of hatch/seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(Datetime,$__interval) as 'time',\n  scanMin/60000 as 'min',\n  scanMax/60000 as 'max',\n  scanAvg/60000 as 'average',\n  raidMin/60000 as 'min time left',\n  raidMax/60000 as 'max time left',\n  raidAvg/60000 as 'average time left',\n  raidActiveMin,\n  raidActiveMax,\n  raidActiveAvg,\n  raidQueueMin,\n  raidQueueMax,\n  raidQueueAvg\n\nFROM stats_prioraid\nWHERE\n  $__timeFilter(datetime) and\n  RPL = '$RPL' \nGROUP BY 1\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Raid time left (minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Raids active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Raid in queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 12 }
   ]
  }
 ]
}