{
 "title": "10. Dragonite log",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RPL",
    "query": "select distinct(rpl) from dragoLog"
   }
  ]
 },
 "panels": [
  { "title": "All modes combined", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "account re-use warning/available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "account switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "rpc errors (1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "rpc erros (2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n$__timeGroup(a.datetime,$__interval) AS \"time\",\r\nifnull(a.rpc4,0)+ifnull(c.rpc4,0)+ifnull(d.rpc4,0) as 'rpc4',\r\nifnull(a.rpc5,0)+ifnull(c.rpc5,0)+ifnull(d.rpc5,0) as 'rpc5',\r\nifnull(a.rpc6,0)+ifnull(c.rpc6,0)+ifnull(d.rpc6,0) as 'rpc6',\r\nifnull(a.rpc7,0)+ifnull(c.rpc7,0)+ifnull(d.rpc7,0) as 'rpc7',\r\nifnull(a.rpc8,0)+ifnull(c.rpc8,0)+ifnull(d.rpc8,0) as 'rpc8',\r\nifnull(a.rpc9,0)+ifnull(c.rpc9,0)+ifnull(d.rpc9,0) as 'rpc9',\r\nifnull(a.rpc11,0)+ifnull(c.rpc11,0)+ifnull(d.rpc11,0) as 'rpc11',\r\nifnull(a.rpc12,0)+ifnull(c.rpc12,0)+ifnull(d.rpc12,0) as 'rpc12',\r\nifnull(a.rpc13,0)+ifnull(c.rpc13,0)+ifnull(d.rpc13,0) as 'rpc13',\r\nifnull(a.rpc14,0)+ifnull(c.rpc14,0)+ifnull(d.rpc14,0) as 'rpc14',\r\nifnull(a.rpc15,0)+ifnull(c.rpc15,0)+ifnull(d.rpc15,0) as 'rpc15',\r\nifnull(a.rpc16,0)+ifnull(c.rpc16,0)+ifnull(d.rpc16,0) as 'rpc16',\r\nifnull(a.rpc17,0)+ifnull(c.rpc17,0)+ifnull(d.rpc17,0) as 'rpc17',\r\nifnull(a.rpc18,0)+ifnull(c.rpc18,0)+ifnull(d.rpc18,0) as 'rpc18',\r\nifnull(a.wsError,0) as 'ws error',\r\nifnull(a.wsClose,0) as 'ws closed',\r\nifnull(a.wsMitmRecon,0) as 'mitm initiated reconnect',\r\nifnull(a.mitmUnknown,0) as 'unknown error',\r\nifnull(a.mitmNoGame,0) as 'game not ready',\r\nifnull(a.mitmLogginIn,0) as 'login in progress',\r\nifnull(a.mitmTokenRej,0) as 'token rejected',\r\nifnull(a.mitmNotLogged,0) as 'not logged in',\r\nifnull(a.mitmLoginErr,0) as 'login error',\r\nifnull(a.proxyBan,0) as 'proxy 3h ptc login ban',\r\nifnull(a.authReq,0) as 'Requesting auth',\r\nifnull(a.login,0) as 'Login successful',\r\nifnull(a.swTotal,0)+ifnull(c.swTotal,0)+ifnull(d.swTotal,0) as 'Accounts rotated',\r\nifnull(a.swWarnSusp,0)+ifnull(c.swWarnSusp,0)+ifnull(d.swWarnSusp,0) as 'Warned',\r\nifnull(a.swBanned,0)+ifnull(c.swBanned,0)+ifnull(d.swBanned,0) as 'Banned',\r\nifnull(a.swDisabled,0)+ifnull(c.swDisabled,0)+ifnull(d.swDisabled,0) as 'Disabled',\r\nifnull(a.swDayLimit,0)+ifnull(c.swDayLimit,0)+ifnull(d.swDayLimit,0) as 'Daily limit',\r\nifnull(a.swRange,0)+ifnull(c.swRange,0)+ifnull(d.swRange,0) as 'Out of range 10 times',\r\nifnull(a.swTime,0)+ifnull(c.swTime,0)+ifnull(d.swTime,0) as 'Max connection time',\r\nifnull(a.swStop,0)+ifnull(c.swStop,0)+ifnull(d.swStop,0) as 'Stop cooldown',\r\nifnull(a.swLLapi,0)+ifnull(c.swLLapi,0)+ifnull(d.swLLapi,0) as 'LLapi',\r\nifnull(a.swQdist,0)+ifnull(c.swQdist,0)+ifnull(d.swQdist,0) as 'Quest distance',\r\nifnull(a.backoff,0)+ifnull(c.backoff,0)+ifnull(d.backoff,0) as 'backoff',\r\nifnull(a.noAccount,0) as 'No accounts available',\r\nifnull(a.released24h,0) as 'released less then 24 hours ago',\r\nifnull(a.released7d,0) as 'released less then 7 days ago',\r\nifnull(a.minAuthT,0) as 'minimum auth time',\r\nifnull(a.maxAuthT,0) as 'maximum auth time',\r\nifnull(a.avgAuthT,0) as 'average auth time'\r\n\r\nFROM dragoLog a\r\nLEFT JOIN dragoLog_invasion c ON a.datetime=c.datetime and a.rpl=c.rpl\r\nLEFT JOIN dragoLog_fort d ON a.datetime=d.datetime and a.rpl=d.rpl \r\nWHERE\r\na.RPL='$RPL'\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(a.datetime,$__interval)"
    }
   ]
  },
  {
   "title": "rpc errors (3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "mitm errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "auth/login",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "mitm connection error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "auth time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "proxy ptc ip banned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Area mode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "rpc errors (1)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      { "panelId": 24 }
     ]
    },
    {
     "title": "area rpc erros (2)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "rawSql": "SELECT\r\n$__timeGroup(datetime,$__interval) AS \"time\",\r\nrpc4,rpc5,rpc6,rpc7,rpc8,rpc9,rpc11,rpc12,rpc13,rpc14,rpc15,rpc16,rpc17,rpc18,\r\n-- noGMO as 'GMO - giving up',\r\n-- gmoPoke as 'Got a GMO: x pokemon',\r\n-- 100*(gmoPoke-gmo0+gmo8)/gmoPoke as 'initial GMO success rate',\r\n-- 100*gmo8/(gmoPoke+gmo8) as 'GMO failure rate 8/8',\r\n-- (gmo0-gmo1)/gmo0 as 'GMO success after retry #1',\r\n-- (gmo1-gmo2)/gmo0 as '#2',\r\n-- (gmo2-gmo3)/gmo0 as '#3',\r\n-- (gmo3-gmo4)/gmo0 as '#4',\r\n-- (gmo4-gmo5)/gmo0 as '#5',\r\n-- (gmo5-gmo6)/gmo0 as '#6',\r\n-- (gmo6-gmo7)/gmo0 as '#7',\r\n-- (gmo7-gmo8)/gmo0 as '#8',\r\n-- gmo0+gmo1+gmo2+gmo3+gmo4+gmo5+gmo6+gmo7 as 'total retry',\r\nifnull(swTotal,0) as 'Accounts rotated',\r\nifnull(swWarnSusp,0) as 'Warned',\r\nifnull(swBanned,0) as 'Banned',\r\nifnull(swDisabled,0) as 'Disabled',\r\nifnull(swDayLimit,0) as 'Daily limit',\r\nifnull(swRange,0) as 'Out of range 10 times',\r\nifnull(swTime,0) as 'Max connection time',\r\nifnull(swStop,0) as 'Stop cooldown',\r\nifnull(swLLapi,0) as 'LLapi',\r\nifnull(swQdist,0) as 'Quest distance',\r\nbackoff\r\nFROM dragoLog\r\n\r\nWHERE\r\nRPL='$RPL'\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(datetime,$__interval)"
      }
     ]
    },
    {
     "title": "rpc errors (3)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      { "panelId": 24 }
     ]
    },
    {
     "title": "account switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      { "panelId": 24 }
     ]
    }
   ]
  },
  {
   "title": "Invasion workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "rpc errors (1)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      { "panelId": 44 }
     ]
    },
    {
     "title": "invasion rpc erros (2)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "rawSql": "SELECT\r\n$__timeGroup(datetime,$__interval) AS \"time\",\r\nrpc4,rpc5,rpc6,rpc7,rpc8,rpc9,rpc11,rpc12,rpc13,rpc14,rpc15,rpc16,rpc17,rpc18,\r\nnoGMO as 'GMO - giving up',\r\ngmoPoke as 'Got a GMO: x pokemon',\r\n100*(gmoPoke-gmo0+gmo8)/gmoPoke as 'initial GMO success rate',\r\n100*gmo8/(gmoPoke+gmo8) as 'GMO failure rate 8/8',\r\n(gmo0-gmo1)/gmo0 as 'GMO success after retry #1',\r\n(gmo1-gmo2)/gmo0 as '#2',\r\n(gmo2-gmo3)/gmo0 as '#3',\r\n(gmo3-gmo4)/gmo0 as '#4',\r\n(gmo4-gmo5)/gmo0 as '#5',\r\n(gmo5-gmo6)/gmo0 as '#6',\r\n(gmo6-gmo7)/gmo0 as '#7',\r\n(gmo7-gmo8)/gmo0 as '#8',\r\ngmo0+gmo1+gmo2+gmo3+gmo4+gmo5+gmo6+gmo7 as 'total retry',\r\nifnull(swTotal,0) as 'Accounts rotated',\r\nifnull(swWarnSusp,0) as 'Warned',\r\nifnull(swBanned,0) as 'Banned',\r\nifnull(swDisabled,0) as 'Disabled',\r\nifnull(swDayLimit,0) as 'Daily limit',\r\nifnull(swRange,0) as 'Out of range 10 times',\r\nifnull(swTime,0) as 'Max connection time',\r\nifnull(swStop,0) as 'Stop cooldown',\r\nifnull(swLLapi,0) as 'LLapi',\r\nifnull(swQdist,0) as 'Quest distance',\r\nbackoff\r\nFROM dragoLog_invasion\r\n\r\nWHERE\r\nRPL='$RPL'\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(datetime,$__interval)"
      }
     ]
    },
    {
     "title": "rpc errors (3)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      { "panelId": 44 }
     ]
    },
    {
     "title": "account switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      { "panelId": 44 }
     ]
    }
   ]
  },
  {
   "title": "Fort workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "rpc errors (1)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      { "panelId": 45 }
     ]
    },
    {
     "title": "fort rpc erros (2)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "rawSql": "SELECT\r\n$__timeGroup(datetime,$__interval) AS \"time\",\r\nrpc4,rpc5,rpc6,rpc7,rpc8,rpc9,rpc11,rpc12,rpc13,rpc14,rpc15,rpc16,rpc17,rpc18,\r\n-- noGMO as 'GMO - giving up',\r\n-- gmoPoke as 'Got a GMO: x pokemon',\r\n-- 100*(gmoPoke-gmo0+gmo8)/gmoPoke as 'initial GMO success rate',\r\n-- 100*gmo8/(gmoPoke+gmo8) as 'GMO failure rate 8/8',\r\n-- (gmo0-gmo1)/gmo0 as 'GMO success after retry #1',\r\n-- (gmo1-gmo2)/gmo0 as '#2',\r\n-- (gmo2-gmo3)/gmo0 as '#3',\r\n-- (gmo3-gmo4)/gmo0 as '#4',\r\n-- (gmo4-gmo5)/gmo0 as '#5',\r\n-- (gmo5-gmo6)/gmo0 as '#6',\r\n-- (gmo6-gmo7)/gmo0 as '#7',\r\n-- (gmo7-gmo8)/gmo0 as '#8',\r\n-- gmo0+gmo1+gmo2+gmo3+gmo4+gmo5+gmo6+gmo7 as 'total retry',\r\nifnull(swTotal,0) as 'Accounts rotated',\r\nifnull(swWarnSusp,0) as 'Warned',\r\nifnull(swBanned,0) as 'Banned',\r\nifnull(swDisabled,0) as 'Disabled',\r\nifnull(swDayLimit,0) as 'Daily limit',\r\nifnull(swRange,0) as 'Out of range 10 times',\r\nifnull(swTime,0) as 'Max connection time',\r\nifnull(swStop,0) as 'Stop cooldown',\r\nifnull(swLLapi,0) as 'LLapi',\r\nifnull(swQdist,0) as 'Quest distance',\r\nbackoff\r\nFROM dragoLog_fort\r\n\r\nWHERE\r\nRPL='$RPL'\r\nGROUP BY 1  \r\nORDER BY $__timeGroup(datetime,$__interval)"
      }
     ]
    },
    {
     "title": "rpc errors (3)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      { "panelId": 45 }
     ]
    },
    {
     "title": "account switch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      { "panelId": 45 }
     ]
    }
   ]
  }
 ]
}