{
 "title": "30. draGOnite dimensioning overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "numQuest", "label": "#Quests/worker", "query": "1200" },
   { "name": "rtt", "label": "rtt (m)" },
   { "name": "locTime", "label": "Location time (s)", "query": "3.6" }
  ]
 },
 "panels": [
  {
   "title": "Area config totals",
   "type": "table",
   "description": "WHERE a.pokemon_mode_workers>0",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(distinct(a.name)) as 'areas',\r\n  sum(a.pokemon_mode_workers) as 'mon worker',\r\n  sum(ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\"))))  as 'mon length',\r\n  sum(ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))) / sum(a.pokemon_mode_workers) as '#mon loc/worker',\r\n  sum(b.stops) as '#stops',\r\n  sum(b.stops) / sum(a.pokemon_mode_workers) as '#quest/worker'\r\n\r\nFROM dragonite.area a\r\nLEFT JOIN blissey.stats_quest_area b ON a.name COLLATE utf8mb4_general_ci = area and b.datetime = concat(date(now() - interval 15 minute),' ', SEC_TO_TIME((TIME_TO_SEC(time(now() - interval 15 minute)) DIV 900) * 900)) and b.rpl =15\r\nWHERE a.pokemon_mode_workers>0"
    }
   ]
  },
  {
   "title": "Area dimensioning totals",
   "type": "table",
   "description": "WHERE a.pokemon_mode_workers>0",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(distinct(a.name)) as 'areas',\r\n  sum(round(2*b.stops/$numQuest,2)) as '#quest_req',\r\n  ceiling(2*sum(b.stops)/$numQuest)-cast(sum(a.quest_mode_workers) as SIGNED) as 'quest_diff',\r\n  sum( round( (($locTime) * ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))) / ($rtt*60) ,2) ) as '#mon_req',\r\n  round(sum( round( (($locTime) * ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))) / ($rtt*60) ,2) )- sum( CAST(a.pokemon_mode_workers AS SIGNED) ) ,0) as 'mon_diff',\r\n  sum(pokemon_mode_workers) as 'current',\r\n  ceiling(greatest(sum(round(2*b.stops/$numQuest,2)),sum( round( (($locTime) * ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))) / ($rtt*60) ,2) )) ) as 'final_req',\r\n  ceiling(greatest(sum(round(2*b.stops/$numQuest,2)),sum( round( (($locTime) * ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))) / ($rtt*60) ,2) )) ) - sum(a.pokemon_mode_workers) as 'final_diff'\r\nFROM dragonite.area a\r\nLEFT JOIN blissey.stats_quest_area b ON a.name COLLATE utf8mb4_general_ci = area and b.datetime = concat(date(now() - interval 15 minute),' ', SEC_TO_TIME((TIME_TO_SEC(time(now() - interval 15 minute)) DIV 900) * 900)) and b.rpl = 15\r\nWHERE a.pokemon_mode_workers>0\r\n"
    }
   ]
  },
  {
   "title": "Area config",
   "type": "table",
   "gridPos": { "h": 126, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  a.name,\r\n  a.pokemon_mode_workers as 'mon worker',\r\n  ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))  as 'mon length',\r\n  ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\"))) / a.pokemon_mode_workers as '#mon loc/worker',\r\n  sum(b.stops) as '#stops',\r\n  2*sum(stops)/(sum(a.pokemon_mode_workers)/count(a.pokemon_mode_workers)) as '#quest/worker'\r\n  \r\nFROM dragonite.area a\r\nLEFT JOIN blissey.stats_quest_area b ON a.name COLLATE utf8mb4_general_ci = area and b.datetime = concat(date(now() - interval 15 minute),' ', SEC_TO_TIME((TIME_TO_SEC(time(now() - interval 15 minute)) DIV 900) * 900)) and b.rpl =15\r\n\r\nGROUP BY a.name\r\nORDER BY a.name"
    }
   ]
  },
  {
   "title": "Area dimensioning",
   "type": "table",
   "gridPos": { "h": 126, "w": 13, "x": 11, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  a.name,\r\n  round(2*sum(b.stops)/$numQuest,2) as '#quest_req',\r\n  (ceiling(2*sum(b.stops)/$numQuest))-cast(a.quest_mode_workers as SIGNED) as 'quest_diff',\r\n  round( (($locTime) * ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))) / ($rtt*60) ,2) as '#mon_req',\r\n  CAST(ceiling( (($locTime) * ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))) / ($rtt*60) ) AS SIGNED) - CAST(a.pokemon_mode_workers AS SIGNED) as 'mon_diff',\r\n  sum(pokemon_mode_workers) as 'current',\r\n  case when a.pokemon_mode_workers>0 then ceiling(greatest(round(2*sum(ifnull(b.stops,0))/$numQuest,2),round( (($locTime) * ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))) / ($rtt*60) ,2)) ) end as 'final_req',\r\n  case when a.pokemon_mode_workers>0 then ceiling((ceiling(greatest(round(2*sum(ifnull(b.stops,0))/$numQuest,2),round( (($locTime) * ROUND((LENGTH(a.pokemon_mode_route)-LENGTH(REPLACE(a.pokemon_mode_route, \",\", \"\"))+1) / (1 * LENGTH(\",\")))) / ($rtt*60) ,2)) ))-a.pokemon_mode_workers) end as 'final_diff'\r\nFROM dragonite.area a\r\nLEFT JOIN blissey.stats_quest_area b ON a.name COLLATE utf8mb4_general_ci = area and b.datetime = concat(date(now() - interval 15 minute),' ', SEC_TO_TIME((TIME_TO_SEC(time(now() - interval 15 minute)) DIV 900) * 900)) and b.rpl =15\r\n\r\nGROUP BY a.name\r\nORDER BY a.name"
    }
   ]
  }
 ]
}