{
 "title": "31. draGOnite accounts",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "dragoniteDS", "query": "mysql" },
   { "name": "blisseyDS", "query": "mysql" },
   { "name": "minimum_account_reuse_hours", "query": "72" }
  ]
 },
 "panels": [
  {
   "title": "#account in db",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(datetime,$__interval) as 'time',\n  dbaccounts,\n  dbaccounts-warn-banned-suspended-authbanned-invalid as 'usable accounts',\n  warn as 'warned',\n  suspended,\n  banned,\n  authbanned,\n  invalid\n  -- disabled,\n  -- inUse as 'in use',\n  -- usedIdle as 'idle_used',\n  -- unusedIdle as 'idle_unused',\n  -- 100*inUse/(inUse+usedIdle+unusedIdle) as '%inuse'\nFROM accounts\nWHERE\n  $__timeFilter(datetime) \n--  rpl = '$RPL' \nGROUP BY 1\nORDER BY $__timeGroup(datetime,$__interval)"
    }
   ]
  },
  {
   "title": "Account overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Bans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "allchansey",
     "rawSql": "select\r\n  datetime,\r\n  banned - COALESCE( LAG(banned) OVER (ORDER BY datetime ASC), banned) AS banned,\r\n  authbanned - COALESCE( LAG(authbanned) OVER (ORDER BY datetime ASC), authbanned) AS authbanned\r\n\r\n\r\nfrom accounts\r\nwhere $__timeFilter(datetime) \r\norder by datetime asc;"
    }
   ]
  },
  {
   "title": "d2 usable accounts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with data as (\r\nselect reusetime as time,count(reusetime) as accounts\r\nfrom\r\n(select\r\n(CASE WHEN last_selected is NULL\r\n  THEN now()\r\n  ELSE\r\n    CASE WHEN from_unixtime(last_selected)<now()-interval '$minimum_account_reuse_hours' hour\r\n      THEN\r\n        CASE WHEN consecutive_disable_count<=1\r\n          THEN\r\n            CASE WHEN from_unixtime(ifnull(last_disabled,0))+interval 3 day < now()\r\n              THEN now()\r\n              ELSE from_unixtime(ifnull(last_disabled,0))+interval 3 day\r\n            END\r\n          ELSE\r\n            CASE WHEN from_unixtime(ifnull(last_disabled,0))+interval 30 day < now()\r\n              THEN now()\r\n              ELSE from_unixtime(ifnull(last_disabled,0))+interval 30 day\r\n            END\r\n        END\r\n      ELSE\r\n        CASE WHEN consecutive_disable_count<=1\r\n          THEN greatest(from_unixtime(ifnull(last_disabled,0))+interval 3 day,from_unixtime(last_selected)+interval '$minimum_account_reuse_hours' hour)\r\n          ELSE greatest(from_unixtime(ifnull(last_disabled,0))+interval 30 day,from_unixtime(last_selected)+interval '$minimum_account_reuse_hours' hour)\r\n        END\r\n    END\r\nEND\r\n) as reusetime\r\n\t\t\r\nfrom account\r\nwhere\r\nsuspended=0 and\r\nbanned=0 and\r\nauth_banned=0 and\r\ninvalid=0 and\r\nwarn_expiration < unix_timestamp()\r\n) a\r\ngroup by reusetime\r\norder by reusetime\r\n)\r\n\r\nselect\r\n  time,\r\n--  accounts,\r\n  sum(accounts) over (order by time) as accounts\r\nfrom data;"
    },
    {
     "dataset": "backend",
     "rawSql": "with data as (\r\nselect reusetime as time,count(reusetime) as accounts\r\nfrom\r\n(select\r\n(CASE WHEN last_selected is NULL\r\n  THEN now()\r\n  ELSE\r\n    CASE WHEN from_unixtime(last_selected)<now()-interval '$minimum_account_reuse_hours' hour\r\n      THEN\r\n        CASE WHEN consecutive_disable_count<=1\r\n          THEN\r\n            CASE WHEN from_unixtime(ifnull(last_disabled,0))+interval 3 day < now()\r\n              THEN now()\r\n              ELSE from_unixtime(ifnull(last_disabled,0))+interval 3 day\r\n            END\r\n          ELSE\r\n            CASE WHEN from_unixtime(ifnull(last_disabled,0))+interval 30 day < now()\r\n              THEN now()\r\n              ELSE from_unixtime(ifnull(last_disabled,0))+interval 30 day\r\n            END\r\n        END\r\n      ELSE\r\n        CASE WHEN consecutive_disable_count<=1\r\n          THEN greatest(from_unixtime(ifnull(last_disabled,0))+interval 3 day,from_unixtime(last_selected)+interval '$minimum_account_reuse_hours' hour)\r\n          ELSE greatest(from_unixtime(ifnull(last_disabled,0))+interval 30 day,from_unixtime(last_selected)+interval '$minimum_account_reuse_hours' hour)\r\n        END\r\n    END\r\nEND\r\n) as reusetime\r\n\t\t\r\nfrom account\r\nwhere\r\nsuspended=0 and\r\nbanned=0 and\r\nauth_banned=0 and\r\ninvalid=0 and\r\nwarn_expiration < unix_timestamp() and\r\nrefresh_token<>'' and\r\nfrom_unixtime(last_refreshed)>now()-interval 28 day\r\n) a\r\ngroup by reusetime\r\norder by reusetime\r\n)\r\n\r\nselect\r\n  time,\r\n--  accounts,\r\n  sum(accounts) over (order by time) as accounts_with_valid_token\r\nfrom data;"
    }
   ]
  },
  {
   "title": "d2 account last_released (hourly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ifnull(left(from_unixtime(last_released),13),left(now(),13)) as '_time',\r\n  count(username) as '#accounts released per hour'  \r\nFROM account\r\nGROUP BY left(from_unixtime(last_released),13)\r\nORDER BY left(from_unixtime(last_released),13)"
    }
   ]
  },
  {
   "title": "Consecutive disabled status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(Datetime,$__interval) as 'time',\r\n  consecDis1 as 'Consecutive disabled <= 1',\r\n  consecDis2 as 'Consecutive disabled = 2',\r\n  consecDis3 as 'Consecutive disabled = 3',\r\n  consecDis4p as 'Consecutive disabled >= 4'\r\nFROM accounts\r\nGROUP BY 1\r\nORDER BY $__timeGroup(Datetime,$__interval)"
    }
   ]
  },
  {
   "title": "% arban tested",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\nnow() as time,\n100*sum(case when ar_ban_state>=0 then 1 else 0 end) / count(username) as '%tested'\n-- sum(case when ar_ban_state=1 then 1 else 0 end) as 'ARban'\nfrom account\nwhere last_selected<unix_timestamp(now()) and banned=0 and auth_banned=0"
    }
   ]
  },
  {
   "title": "% arban check in progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\nnow() as time,\n100*sum(case when ar_ban_state<0 then 1 else 0 end) / count(username) as '%inProgress'\n-- sum(case when ar_ban_state=1 then 1 else 0 end) as 'ARban'\nfrom account\nwhere last_selected<unix_timestamp(now()) and banned=0 and auth_banned=0"
    }
   ]
  },
  {
   "title": "ARban",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\nnow() as time,\n-- sum(case when ar_ban_state is NULL then 1 else 0 end) as 'untested',\nsum(case when ar_ban_state=0 then 1 else 0 end) as 'noARban',\nsum(case when ar_ban_state=1 then 1 else 0 end) as 'ARban'\nfrom account\nwhere last_selected<unix_timestamp(now()) and banned=0 and auth_banned=0\n"
    }
   ]
  },
  {
   "title": "Accounts per domain",
   "type": "table",
   "gridPos": { "h": 52, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "dataset": "backend",
     "rawSql": "select\r\n-- SUBSTRING_INDEX(ifnull(a.email,'unknown'), '@', -1) as domain,\r\ncase when length(ifnull(email,\"unknown\"))-length(replace(ifnull(email,\"unknown\"),\".\",\"\"))>1 then SUBSTRING_INDEX(SUBSTRING_INDEX(ifnull(a.email,'unknown'), '@', -1), '.',-(length(ifnull(email,\"unknown\"))-length(replace(ifnull(email,\"unknown\"),\".\",\"\"))-0)) else SUBSTRING_INDEX(ifnull(a.email,'unknown'), '@', -1) end as domain,\r\n1 as one,\r\ncount(a.username) as accounts,\r\nsum(case when banned=1 then 1 else 0 end) as 'banned',\r\nsum(case when auth_banned>0 then 1 else 0 end) as 'authbanned',\r\nsum(case when refresh_token='' then 1 else 0 end) as noToken,\r\n100*sum(case when refresh_token='' then 1 else 0 end)/count(a.username) as '%NoToken'\r\nfrom account a\r\ngroup by domain"
    }
   ]
  },
  {
   "title": "#accounts per ARattempt",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "select\nnow() as time,\nar_ban_state*-1 as 'spins',\ncount(username) as '#accounts'\nfrom account\nwhere ar_ban_state < 0  and banned=0 and auth_banned=0\ngroup by ar_ban_state\norder by spins"
    }
   ]
  }
 ]
}